version: '3.3'

services:
  typebot-db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  typebot-builder:
    build:
      context: .
      args:
        SCOPE: builder
    labels:
      virtual.host: 'dev.studio.skarlet.ai' # change to your domain
      virtual.port: '3000'
      virtual.tls-email: 'roylan@skarlet.ai' # change to your email
    image: typebot-builder-kpital:latest
    restart: always
    depends_on:
      - typebot-db
    ports:
      - '8080:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: .env

  typebot-viewer:
    labels:
      virtual.host: 'bot.studio.skarlet.ai' # change to your domain
      virtual.port: '3000'
      virtual.tls-email: 'roylan@skarlet.ai' # change to your email
      # Necessary to enable message streaming
      virtual.proxy.directives: |
        flush_interval -1
    image: baptistearno/typebot-viewer:latest
    restart: always
    ports:
      - '8081:3000'
    env_file: .env

  caddy:
    container_name: typebot_caddy_reverse_proxy
    image: caddy:alpine
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    depends_on:
      - typebot-builder
      - typebot-viewer
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  db-data:
  s3_data:
  caddy_data:
  caddy_config:
