// Do not edit this file manually
import { parseBlockSchema } from '@typebot.io/forge'
import { intentionResponseBlock } from '.'

export const intentionResponseBlockSchema = parseBlockSchema(
  intentionResponseBlock
)
