// Do not edit this file manually
import { parseBlockSchema } from '@typebot.io/forge'
import { recoveryUserBlock } from '.'

export const recoveryUserBlockSchema = parseBlockSchema(recoveryUserBlock)
