// Do not edit this file manually
import { parseBlockSchema } from "@typebot.io/forge";
import { transferagentBlock } from ".";

export const transferagentBlockSchema = parseBlockSchema(transferagentBlock);
